name: Build and Deploy to Staging
on:
  push:
    branches:
      - deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # step 3: Set up cache
      - name: Setup cache for meaven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Step 4: Build the JAR
      - name : Installing local dependency
        run : |
          mvn clean install -f pom.xml

      # Step 5: Store deployment data
      - uses: actions/upload-artifact@v4
        with:
          name: nms-jars
          path: |
            api/target/*.jar
            csv/target/*.jar
            flw/target/*.jar
            flwUpdate/target/*.jar
            imi/target/*.jar
            kilkari/target/*.jar
            mcts/target/*.jar
            mobile-academy/target/*.jar
            props/target/*.jar
            rch/target/*.jar
            region/target/*.jar
            rejection-handler/target/*.jar
            testing/target/*.jar
            tracking/target/*.jar 
